services:
  # ollama:
  #   image: ollama/ollama:0.6.7
  #   env_file: .env
  #   ports:
  #     - "11434:11434"
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped
  #   volumes:
  #     - ollama-local:/root/.ollama
  #     - ./entrypoint.sh:/entrypoint.sh
  #     - ./logs:/logs
  #   entrypoint: [ "/bin/bash", "/entrypoint.sh" ]
  #   healthcheck:
  #     test: curl --fail http://localhost:11434 || exit 1
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage
volumes:
  qdrant:
