services:
  # ollama:
  #   image: ollama/ollama:0.6.7
  #   env_file: .env
  #   ports:
  #     - "11434:11434"
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped
  #   volumes:
  #     - ollama-local:/root/.ollama
  #     - ./entrypoint.sh:/entrypoint.sh
  #     - ./logs:/logs
  #   entrypoint: [ "/bin/bash", "/entrypoint.sh" ]

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage
  backend:
    build: ./backend
    restart: always
    env_file: .env
    depends_on:
      - qdrant
    ports:
      - "3000:3000"
   
    extra_hosts:
    - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
volumes:
  qdrant:
